### PR TITLE
Add Snap support

### PR DESCRIPTION
**Pull request by EricZhang456**
I already have a Snap live at https://snapcraft.io/certbot-dns-dnspod

### CODE REVIEW

**Comment by tengattack** [comment]
Thank you

**Comment by EricZhang456** [comment]
This fixes #10 btw

**Comment by EricZhang456** [comment]
btw check the comment in snap/snapcraft.yaml

**Comment by tengattack** [comment]
> btw check the comment in snap/snapcraft.yaml

@EricZhang456 ：)

https://github.com/tengattack/certbot-dns-dnspod/commit/e94bc6ffaae635166a4bae6ef53ce6274f9ae40b

**Comment by tengattack** [comment]
BTW, did you build Snap package in Docker or Local Machine? I want to configure a GitHub pipeline to do it automatically after publishing a version.

**Comment by EricZhang456** [comment]
> BTW, did you build Snap package in Docker or Local Machine? I want to configure a GitHub pipeline to do it automatically after publishing a version.

Local. Also check your inbox (tengattack@gmail.com), I have sent an invitation for Snap package collaboration

**Comment by EricZhang456** [comment]
GitHub Pipeline is not necessary anymore. The Snap Store has a new feature that allows building Snap package directly from the GitHub repo. 

Side note though, my Snap currently requires manual review as I have a support website specified.

> Thu 23 Dec. 2021
> 
> 批准 by Maria Emilia Torino. “Manually approving since the support for links is not added yet to the automated review” — Maria Emilia Torino

**Comment by tengattack** [comment]
> > BTW, did you build Snap package in Docker or Local Machine? I want to configure a GitHub pipeline to do it automatically after publishing a version.
> 
> Local. Also check your inbox ([tengattack@foxmail.com](mailto:tengattack@foxmail.com)), I have sent an invitation for Snap package collaboration

Could you send the invitation to my gmail ([tengattack@gmail.com](mailto:tengattack@gmail.com))

**Comment by tengattack** [comment]
> GitHub Pipeline is not necessary anymore. The Snap Store has a new feature that allows building Snap package directly from the GitHub repo.
> 
> Side note here, my Snap currently requires manual review as I have a support website specified. It's a new feature in Snapcraft 5.0 and has not been added to the automatic review tool. More info [here](https://snapcraft.io/docs/snapcraft-top-level-metadata).
> 
> > Thu 23 Dec. 2021
> > 批准 by Maria Emilia Torino. “Manually approving since the support for links is not added yet to the automated review” — Maria Emilia Torino

Thank you, I will try it later

**Comment by EricZhang456** [comment]
> > > BTW, did you build Snap package in Docker or Local Machine? I want to configure a GitHub pipeline to do it automatically after publishing a version.
> > 
> > 
> > Local. Also check your inbox ([tengattack@foxmail.com](mailto:tengattack@foxmail.com)), I have sent an invitation for Snap package collaboration
> 
> Could you send the invitation to my gmail ([tengattack@gmail.com](mailto:tengattack@gmail.com))? I already have the account on Snap.

Sure

**Pull request merged**
