### PR TITLE
Fix error while add_txt_record.

### PR DESCRIPTION
**Pull request by huww98**
I got error when trying to obtain certification.

```
Unexpected error determining zone identifier for cn: Domain name invalid, please input tld domain
```

I have fixed this

### CODE REVIEW

**Comment by tengattack** [comment]
But if we try to obtain certification for sub domain like `foo.bar.example.com`, will it work?

**Comment by huww98** [comment]
I think it will work.

https://github.com/certbot/certbot/blob/v0.26.1/certbot/plugins/dns_common.py#L326-L327

It will try every possible domain.

**Comment by tengattack** [comment]
Are you tring to obtain top-level domain like `foo.cn`?

**Comment by huww98** [comment]
Yes

**Comment by tengattack** [comment]
OK thank you!

**Comment by huww98** [comment]
I have just tested that it does **not** work for something like `foo.bar.example.com`, I will trying to figure out why.

**Comment by tengattack** [comment]
Maybe we should determine whether the domain is top-level domain

**Comment by huww98** [comment]
Fixed that. I have successfully obtained a certification for `foo.bar.<mydomain>.con`

**Comment by tengattack** [comment]
Great works!

**Pull request merged**
